name: radio_beats
description: Listen to FM radio.
homepage: https://github.com/realth000/radio_beats
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  audio_service: ^0.18.12
  audioplayers: ^5.2.0
  # Version constrained by flutter sdk
  collection: any
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^12.0.1
  hooks_riverpod: ^2.4.5
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  surf_lint_rules: ^3.0.0
  window_manager: ^0.3.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/default_radio.txt
